
services:
  app:
    build: .
    ports:
      - "8000:80"
    env_file:
      - .env
    environment:
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/html/database/database.sqlite
    volumes:
      - ./database:/var/www/html/database
      - ./storage:/var/www/html/storage
      - ./.env:/var/www/html/.env:ro
